- name: copia keys al appserver
  copy: src="files/{{eidas_version}}/eID4U-idp-demo/keys/" dest="{{ config_ruta }}/keystore" owner=jboss group=jboss

- name: copia config al appserver
  copy: src="files/{{eidas_version}}/eID4U-idp-demo/config/" dest="{{ config_ruta }}/jboss/idp" owner=jboss group=jboss

- name: copia war al appserver
  copy: src="files/{{eidas_version}}/eID4U-idp-demo/IdP.war" dest="{{ wars_ruta }}" owner=jboss group=jboss
