---
- hosts: maquina_peter
  tasks:
  - name: Copia additional attribs node
    copy: src=files/saml-engine-additional-attributes.xml backup=yes dest="{{ruta_config}}/jboss/"
  - name: Copia additional attribs node custom
    copy: src=files/saml-engine-additional-attributes.xml backup=yes dest="{{ruta_config}}/jboss/saml-engine-additional-attributes_EidasNode.xml"
  - name: Copia additional attribs idp
    copy: src=files/saml-engine-additional-attributes.xml backup=yes dest="{{ruta_config}}/jboss/idp/"
  - name: Copia additional attribs sp
    copy: src=files/saml-engine-additional-attributes.xml backup=yes dest="{{ruta_config}}/jboss/sp/"
  - name: Copia additional attribs sp custom
    copy: src=files/saml-engine-additional-attributes.xml backup=yes dest="{{ruta_config}}/jboss/sp/saml-engine-additional-attributes_SP.xml"




