---
- hosts: "{{ mi_host | default('localhost') }}"
  tasks:
  - name: Copia additional attribs node
    copy: src=saml-engine-additional-attributes.xml backup=yes dest="{{config_ruta}}/{{app_server}}/"
  - name: Copia additional attribs node custom
    copy: src=saml-engine-additional-attributes.xml backup=yes dest="{{config_ruta}}/{{app_server}}/saml-engine-additional-attributes_EidasNode.xml"
  - name: Copia additional attribs idp
    copy: src=saml-engine-additional-attributes.xml backup=yes dest="{{config_ruta}}/{{app_server}}/idp/"
  - name: Copia additional attribs sp
    copy: src=saml-engine-additional-attributes.xml backup=yes dest="{{config_ruta}}/{{app_server}}/sp/"
  - name: Copia additional attribs sp custom
    copy: src=saml-engine-additional-attributes.xml backup=yes dest="{{config_ruta}}/{{app_server}}/sp/saml-engine-additional-attributes_SP.xml"
  - name: Fuerza redepoy IdP
    copy: content="" dest="{{deploy_ruta}}/IdP.war.dodeploy"
    when: app_server == "jboss"
  - name: Fuerza redepoy SP
    copy: content="" dest="{{deploy_ruta}}/SP.war.dodeploy"
    when: app_server == "jboss"
  - name: Fuerza redepoy IdP
    copy: content="" dest="{{deploy_ruta}}/EidasNode.war.dodeploy"
    when: app_server == "jboss"

