- name: instalar git
  apt: name=git state=present version="{{eidas_version}}"
  when: de_fuentes

- name: Bajar repo eidas
  git: repo ="{{ eidas_repo }}" dest="{{ eidas_ruta }}"
  when: de_fuentes

- name: compilar con maven
  shell: "cd {{eidas_ruta}}/EIDAS-Parent;mvn clean install -P jBoss7"
  when: de_fuentes

- name: copiar a servidor
  copy: src="{{artifacts_ruta}}" dest="{{wars_ruta}}"
  when: de_fuentes

- name: copia keys al appserver
  copy: src="{{eidas_version}}/keys/" dest="{{ config_ruta }}/keystore" owner=jboss group=jboss


- name: asegura appserver configdir
  file: path="{{ config_ruta }}/{{app_server}}" state=directory

- name: asegura configdir idp
  file: path="{{ config_ruta }}/{{app_server}}/specific" state=directory

- name: copia config al appserver
  template: src={{ item }} dest="{{ config_ruta }}/{{app_server}}/" owner=jboss group=jboss
  with_fileglob:
  - files/{{eidas_version}}/config/*.*

- name: copia specific config al appserver
  template: src={{ item }} dest="{{ config_ruta }}/{{app_server}}/specific/" owner=jboss group=jboss
  with_fileglob:
  - files/{{eidas_version}}/config/specific/*.*

- name: copia war al appserver
  copy: src="{{eidas_version}}/EidasNode.war" dest="{{ wars_ruta }}" owner=jboss group=jboss

- name: fuerza redeploy war
  copy: content="" dest="{{ wars_ruta }}/EidasNode.war.dodeploy" owner=jboss group=jboss