- name: instalar git
  apt: name=git state=present version="{{eidas_version}}"
  when: de_fuentes

- name: Bajar repo eidas
  git: repo ="{{ eidas_repo }}" dest="{{ eidas_ruta }}"
  when: de_fuentes

- name: compilar con maven
  shell: "cd {{eidas_ruta}}/EIDAS-Parent;mvn clean install -P jBoss7"
  when: de_fuentes

- name: copiar a servidor
  copy: src="{{artifacts_ruta}}" dest="{{wars_ruta}}"
  when: de_fuentes

- name: copia keys al appserver
  copy: src="files/{{eidas_version}}/eID4U-node/keys/" dest="{{ config_ruta }}/keystore" owner=jboss group=jboss

- name: copia config al appserver
  copy: src="files/{{eidas_version}}/eID4U-node/config/" dest="{{ config_ruta }}/jboss" owner=jboss group=jboss

- name: copia war al appserver
  copy: src="files/{{eidas_version}}/eID4U-node/EidasNode.war" dest="{{ wars_ruta }}" owner=jboss group=jboss
